/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        background: '#faf8ff',
        'on-primary': '#ffffff',
        'surface-container-highest': '#dae2fd',
        'surface-dim': '#d2d9f4',
        'on-secondary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#005236',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#002113',
        'primary-fixed': '#dde1ff',
        'on-primary-fixed': '#001452',
        'inverse-on-surface': '#eef0ff',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#b7c4ff',
        'on-surface-variant': '#434656',
        'inverse-surface': '#283044',
        primary: '#003ec7',
        'outline-variant': '#c3c5d9',
        'inverse-primary': '#b7c4ff',
        'surface-bright': '#faf8ff',
        tertiary: '#005a3c',
        error: '#ba1a1a',
        secondary: '#505f76',
        'on-background': '#131b2e',
        'secondary-fixed': '#d3e4fe',
        'error-container': '#ffdad6',
        'tertiary-container': '#007550',
        'surface-variant': '#dae2fd',
        'surface-container-low': '#f2f3ff',
        'primary-container': '#0052ff',
        'surface-container-high': '#e2e7ff',
        'surface-tint': '#004ced',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary': '#ffffff',
        'on-surface': '#131b2e',
        'secondary-container': '#d0e1fb',
        'on-primary-container': '#dfe3ff',
        outline: '#737688',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed-variant': '#38485d',
        'tertiary-fixed': '#6ffbbe',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eaedff',
        'on-secondary-container': '#54647a',
        'on-primary-fixed-variant': '#0038b6',
        'on-tertiary-container': '#72fec0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '48px',
        'margin-desktop': '64px',
        base: '4px',
        'margin-mobile': '16px',
        xs: '8px',
        xl: '80px',
        sm: '16px',
        gutter: '24px',
        md: '24px',
      },
      fontFamily: {
        'label-md': ['Geist'],
        'headline-lg-mobile': ['Geist'],
        'body-md': ['Inter'],
        'label-sm': ['Geist'],
        'body-lg': ['Inter'],
        'headline-lg': ['Geist'],
        'headline-md': ['Geist'],
        'display-lg': ['Geist'],
        'display-lg-mobile': ['Geist'],
      },
      fontSize: {
        'label-md': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-lg-mobile': [
          '24px',
          { lineHeight: '32px', fontWeight: '600' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'display-lg-mobile': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
      },
    },
  },
  plugins: [],
};
